/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package credito;

import credito.model.CartaoCredito;
import credito.model.Compra;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        var console = new Scanner(System.in);
        var continueInput = true;

        System.out.print("Digite o limite do cartão: ");
        var input = console.nextDouble();
        var cartao = new CartaoCredito(input);

        while (continueInput) {
            System.out.print("Digite a descrição da compra:");
            var compraDescricao = console.next();
            System.out.print("Digite o valor da compra:");
            var compraValor = console.nextDouble();
            var compra = new Compra(compraDescricao, compraValor);
            try {
                cartao.comprar(compra);
            } catch (IllegalStateException e) {
                System.out.println("Saldo insuficiente!");
                break;
            } catch (Exception e) {
                System.out.println("Ocorreu alguma falha no sistema.");
                e.printStackTrace();
            }
            System.out.println("Deseja inserir outra compra? (1 -> sim, 0 -> não)");
            var choice = console.nextInt();
            continueInput = !(choice == 0);
        }

        System.out.println("COMPRAS REALIZADAS:");
        cartao.getCompras().forEach(System.out::println);
    }
}
